import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/global/navbar";
import Footer from "@/components/global/footer";

import { noto_sans } from "@/app/fonts/font";

export const metadata: Metadata = {
  title: "DNIL",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${noto_sans.className}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
